#!/usr/bin/env bash
#
# run_sweep.sh — One-stop configuration and execution for the DESTINY sweeper.
#
# Usage:
#   1. Edit the CONFIGURATION section below
#   2. Run:  ./run_sweep.sh
#
# The script will auto-build the C++ sweeper if the source is newer than the
# binary, generate a config file from the settings below, then run the sweep.
#
# Output (inside CONFIG_DIR/OUTPUT_DIR):
#   destiny_sweep_results.csv   — all rows, all capacities
#   pareto_<capacity>.csv       — per-capacity Pareto-filtered CSVs

set -euo pipefail

# ============================================================
#  CONFIGURATION — edit these to control the sweep
# ============================================================

# Path to the config/ directory containing .cfg and .cell files.
# (Relative to this script, or absolute.)
CONFIG_DIR="destiny_3d_cache/config"

# DESTINY binary path (relative to CONFIG_DIR).
DESTINY_PATH="../destiny"

# Template .cfg files to sweep (relative to CONFIG_DIR).
TEMPLATES=(
    sample_2D_eDRAM.cfg
    sample_3D_eDRAM.cfg
    sample_2DReRAM.cfg
    sample_3DReRAM.cfg
    sample_PCRAM.cfg
    sample_STTRAM.cfg
    sample_SRAM_2layer.cfg
    sample_SRAM_4layer.cfg
)

# Capacities to test.
CAPACITIES_KB=(32 64 128 256 512 1024)
CAPACITIES_MB=(1 2 4 8)

# Optimisation-target sweep.
SWEEP_OPT_TARGETS=true
OPT_TARGETS=(
    WriteEDP
    ReadLatency
    WriteLatency
    ReadDynamicEnergy
    WriteDynamicEnergy
    Full
)

# Cell-file swapping (cross-technology sweep).
SWAP_CELL_FILES=false
CELL_FILES=()   # leave empty to auto-discover *.cell when SWAP_CELL_FILES=true

# Output directory name (created inside CONFIG_DIR).
OUTPUT_DIR="sweep_out"
CSV_NAME="destiny_sweep_results.csv"

# Max allowed failures before stopping (leave empty for unlimited).
MAX_FAILURES=10

# ============================================================
#  SCRIPT LOGIC — no need to edit below this line
# ============================================================

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWEEPER_SRC="$REPO_ROOT/sweeps/sweep_destiny.cpp"
SWEEPER_BIN="$REPO_ROOT/sweeps/sweep_destiny"
ABS_CONFIG_DIR="$REPO_ROOT/$CONFIG_DIR"

# --- Sanity checks ---
if [[ ! -f "$SWEEPER_SRC" ]]; then
    echo "[ERROR] Sweeper source not found: $SWEEPER_SRC" >&2
    exit 2
fi
if [[ ! -d "$ABS_CONFIG_DIR" ]]; then
    echo "[ERROR] Config directory not found: $ABS_CONFIG_DIR" >&2
    exit 2
fi

# --- Build if source is newer than binary ---
if [[ ! -x "$SWEEPER_BIN" ]] || [[ "$SWEEPER_SRC" -nt "$SWEEPER_BIN" ]]; then
    echo "[build] Compiling sweep_destiny ..."
    g++ -std=c++17 -O2 -Wall "$SWEEPER_SRC" -o "$SWEEPER_BIN"
    echo "[build] Done."
fi

# --- Generate a temporary config file ---
CFG_FILE="$(mktemp)"
trap 'rm -f "$CFG_FILE"' EXIT

{
    echo "# Auto-generated by run_sweep.sh — $(date)"
    echo "destiny_path: $DESTINY_PATH"
    echo "output_dir:   $OUTPUT_DIR"
    echo "csv_name:     $CSV_NAME"
    echo "sweep_opt_targets: $SWEEP_OPT_TARGETS"
    echo "swap_cell_files:   $SWAP_CELL_FILES"

    if [[ -n "${MAX_FAILURES:-}" ]]; then
        echo "max_failures: $MAX_FAILURES"
    else
        echo "max_failures: none"
    fi

    for t in "${TEMPLATES[@]}";      do echo "template:    $t"; done
    for c in "${CAPACITIES_KB[@]}";  do echo "capacity_kb: $c"; done
    for c in "${CAPACITIES_MB[@]}";  do echo "capacity_mb: $c"; done
    for o in "${OPT_TARGETS[@]}";    do echo "opt_target:  $o"; done

    if [[ ${#CELL_FILES[@]} -gt 0 ]]; then
        for f in "${CELL_FILES[@]}"; do echo "cell_file:   $f"; done
    fi
} > "$CFG_FILE"

# --- Run the sweep from config/ ---
echo ""
echo "=== Starting DESTINY sweep ==="
echo "  Config dir : $ABS_CONFIG_DIR"
echo "  Templates  : ${#TEMPLATES[@]}"
echo "  Capacities : ${CAPACITIES_KB[*]} KB  /  ${CAPACITIES_MB[*]} MB"
echo "  Opt targets: ${SWEEP_OPT_TARGETS}"
echo ""

cd "$ABS_CONFIG_DIR"
exec "$SWEEPER_BIN" "$CFG_FILE"
